### ISSUE TITLE
Lauda vs timeit

### ISSUE THREAD

**Issue by IanEdington** [astagi/lauda#4]
Hey @astagi,

I guess this isn't really an issue. I wish Github had a more clear discussion section. I really like how simple this is to implement. I have struggled with implementing timeit in the past. However, through those struggles I learned that timing in python is not usually as simple as start stop.

How does this differ from the builtin timeit module?

What are the use cases where this would be better/worse than timeit?

Thanks again for this succinct implementation.

**Comment by astagi** [comment]
Hi @IanEdington ,

sorry for my late response and thanks! Well, I've never used timeit, but I suppose that timeit builtin module is really really more accurate than Lauda to measure timing, also it expects to receive a string of code. Lauda is just a wrapper around a start and stop mechanism that sometimes you need to implement to detect performance bottleneck in your code. Timing depends on a lot of things when your code is running, but when you see that a function call or a piece of code takes 6-7 seconds and you didn't expect that, you can start asking yourself some questions about the implementation and Lauda can help you doing a fine-grained measurement.

**Comment by IanEdington** [comment]
Cool good to know. I like how easy it it.

**Comment by astagi** [comment]
Thanks :smile: I'll close this "issue" then! :smile:
